services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - client-node-modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - server-node-modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

volumes:
  client-node-modules:
  server-node-modules: