services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - client-node-modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  client-node-modules: