services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - client-node-modules:/usr/src/app/node_modules
    env_file:
      - .env

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - server-node-modules:/usr/src/app/node_modules
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  client-node-modules:
  server-node-modules: